# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_users', '0026_userprofile_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='genre',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=10, null=True, verbose_name='gender'),
        ),
    ]
