# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_users', '0027_auto_20170418_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20, verbose_name='Gender'),
        ),
    ]
