# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_users', '0029_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='set_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
