# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-30 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_users', '0032_auto_20170525_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_attempt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
