# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-31 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_users', '0033_auto_20170530_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exceeded_login_attempts',
            field=models.BooleanField(default=False),
        ),
    ]
