# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_users', '0034_user_exceeded_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone 2'),
        ),
    ]
